import type { Conversation, Message } from "@/types/chat";

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participantId: "user-2",
    participant: {
      id: "user-2",
      name: "Sarah Wilson",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
      online: true,
    },
    lastMessage: {
      id: "msg-1",
      content: "Hey! How are you doing?",
      senderId: "user-2",
      receiverId: "1",
      conversationId: "conv-1",
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      type: "text",
      status: "delivered",
    },
    unreadCount: 2,
    updatedAt: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: "conv-2",
    participantId: "user-3",
    participant: {
      id: "user-3",
      name: "Mike Johnson",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
      online: false,
      lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    lastMessage: {
      id: "msg-2",
      content: "Let's catch up tomorrow!",
      senderId: "1",
      receiverId: "user-3",
      conversationId: "conv-2",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "conv-3",
    participantId: "user-4",
    participant: {
      id: "user-4",
      name: "Emma Davis",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
      online: true,
    },
    lastMessage: {
      id: "msg-3",
      content: "Thanks for your help! 😊",
      senderId: "user-4",
      receiverId: "1",
      conversationId: "conv-3",
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "conv-4",
    participantId: "user-5",
    participant: {
      id: "user-5",
      name: "Alex Brown",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
      online: false,
      lastSeen: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    lastMessage: {
      id: "msg-4",
      content: "See you at the meeting!",
      senderId: "1",
      receiverId: "user-5",
      conversationId: "conv-4",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
];

export const mockMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1-1",
      content: "Hi! How's your project going?",
      senderId: "1",
      receiverId: "user-2",
      conversationId: "conv-1",
      timestamp: new Date(Date.now() - 30 * 60 * 1000),
      type: "text",
      status: "read",
    },
    {
      id: "msg-1-2",
      content: "It's going great! Just finished the frontend part.",
      senderId: "user-2",
      receiverId: "1",
      conversationId: "conv-1",
      timestamp: new Date(Date.now() - 25 * 60 * 1000),
      type: "text",
      status: "delivered",
    },
    {
      id: "msg-1-3",
      content: "That's awesome! Can you send me a screenshot?",
      senderId: "1",
      receiverId: "user-2",
      conversationId: "conv-1",
      timestamp: new Date(Date.now() - 20 * 60 * 1000),
      type: "text",
      status: "read",
    },
    {
      id: "msg-1-4",
      content: "Hey! How are you doing?",
      senderId: "user-2",
      receiverId: "1",
      conversationId: "conv-1",
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      type: "text",
      status: "delivered",
    },
  ],
  "conv-2": [
    {
      id: "msg-2-1",
      content: "Hey Mike! Are you free tomorrow?",
      senderId: "1",
      receiverId: "user-3",
      conversationId: "conv-2",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
    {
      id: "msg-2-2",
      content: "Let's catch up tomorrow!",
      senderId: "1",
      receiverId: "user-3",
      conversationId: "conv-2",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
  ],
  "conv-3": [
    {
      id: "msg-3-1",
      content: "Hi Emma! Did you get the files I sent?",
      senderId: "1",
      receiverId: "user-4",
      conversationId: "conv-3",
      timestamp: new Date(Date.now() - 25 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
    {
      id: "msg-3-2",
      content: "Yes! They were perfect. Working on it now.",
      senderId: "user-4",
      receiverId: "1",
      conversationId: "conv-3",
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
    {
      id: "msg-3-3",
      content: "Thanks for your help! 😊",
      senderId: "user-4",
      receiverId: "1",
      conversationId: "conv-3",
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
  ],
  "conv-4": [
    {
      id: "msg-4-1",
      content: "Don't forget about the meeting tomorrow at 10 AM.",
      senderId: "user-5",
      receiverId: "1",
      conversationId: "conv-4",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
    {
      id: "msg-4-2",
      content: "See you at the meeting!",
      senderId: "1",
      receiverId: "user-5",
      conversationId: "conv-4",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      type: "text",
      status: "read",
    },
  ],
};
